---

- hosts: localhost
  become: True
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
    - name: install docker
      apt:
        name: docker
        state: present
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: install required packages
      pip:
        name: docker-py
        state: present
    - name: Create container
      docker_container:
        name: nodeapp
        image: phamsyhung1110/node-app:{{tag}}
        published_ports: ["8080:8080"]
